-- proposals: immutable meal proposals (issue #48 / PRD v2 §3.1 / ADD §Multi-User).
--
-- Stores the server-resolved, immutable proposal bytes generated by the log_meal
-- tool. Proposals are user-scoped, created in "proposed" status, and transitioned
-- to "committed" or "rejected" on user confirmation. The proposal id is referenced
-- by meal_logs.proposal_id to establish write lineage (issue #37 / ADD Phase 3).
--
-- Proposals are immutable once created — status transitions update only the status
-- column; all nutrition data is frozen at creation time.

create table if not exists public.proposals (
  id               text primary key,
  user_id          uuid not null,
  food_id          text not null,
  food_name        text not null,
  canonical_name   text not null,
  portion_g        numeric not null check (portion_g > 0),
  meal_type        text not null default 'snack',
  kcal             numeric not null,
  protein_g        numeric not null,
  fat_g            numeric not null,
  carbs_g          numeric not null,
  nutrition_source text not null,
  match_type       text not null,
  allergen_tags    text[] not null default '{}',
  status           text not null default 'proposed',
  created_at       timestamptz not null default now()
);

-- Look up a proposal by id (commit/decline path).
create index if not exists proposals_id_idx
  on public.proposals (id);

-- List proposals for a user, ordered by creation time.
create index if not exists proposals_user_created_idx
  on public.proposals (user_id, created_at desc);
